/*
 * JS for apply generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '8d1c3d87-037c-46f1-9d3b-d76370ba131a';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "apply",
    "location": "apply.html"
}];

function apply_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_26': 'apply_mobilelabel_26',
        'spacer_27': 'apply_spacer_27',
        'mobilelabel_2': 'apply_mobilelabel_2',
        'mobilelabel_14': 'apply_mobilelabel_14',
        'spacer_21': 'apply_spacer_21',
        'mobilelabel_15': 'apply_mobilelabel_15',
        'spacer_16': 'apply_spacer_16',
        'mobilelabel_23': 'apply_mobilelabel_23',
        'mobilelabel_22': 'apply_mobilelabel_22',
        'mobilelabel_24': 'apply_mobilelabel_24',
        'spacer_25': 'apply_spacer_25',
        'mobilelabel_13': 'apply_mobilelabel_13',
        'mobilecollapsibleset_3': 'apply_mobilecollapsibleset_3',
        'mobilecollapsblock_4': 'apply_mobilecollapsblock_4',
        'mobilecollapsblockheader_5': 'apply_mobilecollapsblockheader_5',
        'mobilecollapsblockcontent_6': 'apply_mobilecollapsblockcontent_6',
        'mobilelabel_20': 'apply_mobilelabel_20',
        'mobilebutton_17': 'apply_mobilebutton_17',
        'mobilecollapsblock_7': 'apply_mobilecollapsblock_7',
        'mobilecollapsblockheader_8': 'apply_mobilecollapsblockheader_8',
        'mobilecollapsblockcontent_9': 'apply_mobilecollapsblockcontent_9',
        'mobilebutton_18': 'apply_mobilebutton_18',
        'mobilecollapsblock_10': 'apply_mobilecollapsblock_10',
        'mobilecollapsblockheader_11': 'apply_mobilecollapsblockheader_11',
        'mobilecollapsblockcontent_12': 'apply_mobilecollapsblockcontent_12',
        'mobilebutton_19': 'apply_mobilebutton_19'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'apply';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var apply_onLoad = function() {
            apply_elementsExtraJS();

            apply_deviceEvents();
            apply_windowEvents();
            apply_elementsEvents();
        };

    // screen window events


    function apply_windowEvents() {

        $('#apply').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function apply_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function apply_elementsExtraJS() {
        // screen (apply) extra code

        /* mobilecollapsblock_4 */

        $("#apply_mobilecollapsblock_4 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_7 */

        $("#apply_mobilecollapsblock_7 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_10 */

        $("#apply_mobilecollapsblock_10 .ui-collapsible-heading-toggle").attr("tabindex", "1");

    };

    // screen elements handler


    function apply_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#apply_mobilecontainer [name="mobilebutton_17"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://github.com/blackaquaindia/TheBulkShoutout/raw/master/The_Bulk_Shoutout_Certified_v1.0.1_for_Android_4.1.2.apk', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');

                }
            },
        }, '#apply_mobilecontainer [name="mobilebutton_17"]');

    };

    $(document).off("pagebeforeshow", "#apply").on("pagebeforeshow", "#apply", function(event, ui) {
        Apperyio.CurrentScreen = "apply";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    apply_onLoad();
};

$(document).off("pagecreate", "#apply").on("pagecreate", "#apply", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    apply_js();
});
