/*
 * JS for customize generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '8d1c3d87-037c-46f1-9d3b-d76370ba131a';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "customize",
    "location": "customize.html"
}];

function customize_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_26': 'customize_mobilelabel_26',
        'spacer_27': 'customize_spacer_27',
        'mobilelabel_2': 'customize_mobilelabel_2',
        'mobilelabel_14': 'customize_mobilelabel_14',
        'spacer_21': 'customize_spacer_21',
        'mobilelabel_15': 'customize_mobilelabel_15',
        'spacer_16': 'customize_spacer_16',
        'mobilelabel_23': 'customize_mobilelabel_23',
        'mobilelabel_22': 'customize_mobilelabel_22',
        'mobilelabel_24': 'customize_mobilelabel_24',
        'spacer_25': 'customize_spacer_25',
        'mobilelabel_13': 'customize_mobilelabel_13',
        'mobilecollapsibleset_3': 'customize_mobilecollapsibleset_3',
        'mobilecollapsblock_4': 'customize_mobilecollapsblock_4',
        'mobilecollapsblockheader_5': 'customize_mobilecollapsblockheader_5',
        'mobilecollapsblockcontent_6': 'customize_mobilecollapsblockcontent_6',
        'mobilelabel_20': 'customize_mobilelabel_20',
        'mobilebutton_17': 'customize_mobilebutton_17',
        'mobilecollapsblock_7': 'customize_mobilecollapsblock_7',
        'mobilecollapsblockheader_8': 'customize_mobilecollapsblockheader_8',
        'mobilecollapsblockcontent_9': 'customize_mobilecollapsblockcontent_9',
        'mobilebutton_18': 'customize_mobilebutton_18',
        'mobilecollapsblock_10': 'customize_mobilecollapsblock_10',
        'mobilecollapsblockheader_11': 'customize_mobilecollapsblockheader_11',
        'mobilecollapsblockcontent_12': 'customize_mobilecollapsblockcontent_12',
        'mobilebutton_19': 'customize_mobilebutton_19'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'customize';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var customize_onLoad = function() {
            customize_elementsExtraJS();

            customize_deviceEvents();
            customize_windowEvents();
            customize_elementsEvents();
        };

    // screen window events


    function customize_windowEvents() {

        $('#customize').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function customize_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function customize_elementsExtraJS() {
        // screen (customize) extra code

        /* mobilecollapsblock_4 */

        $("#customize_mobilecollapsblock_4 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_7 */

        $("#customize_mobilecollapsblock_7 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_10 */

        $("#customize_mobilecollapsblock_10 .ui-collapsible-heading-toggle").attr("tabindex", "1");

    };

    // screen elements handler


    function customize_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#customize_mobilecontainer [name="mobilebutton_17"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://github.com/blackaquaindia/TheBulkShoutout/raw/master/The_Bulk_Shoutout_Certified_v1.0.1_for_Android_4.1.2.apk', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');

                }
            },
        }, '#customize_mobilecontainer [name="mobilebutton_17"]');

    };

    $(document).off("pagebeforeshow", "#customize").on("pagebeforeshow", "#customize", function(event, ui) {
        Apperyio.CurrentScreen = "customize";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    customize_onLoad();
};

$(document).off("pagecreate", "#customize").on("pagecreate", "#customize", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    customize_js();
});
