/*
 * JS for Offer1250 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '8d1c3d87-037c-46f1-9d3b-d76370ba131a';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Offer1250",
    "location": "Offer1250.html"
}];

function Offer1250_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_26': 'Offer1250_mobilelabel_26',
        'spacer_27': 'Offer1250_spacer_27',
        'mobilelabel_2': 'Offer1250_mobilelabel_2',
        'mobilelabel_14': 'Offer1250_mobilelabel_14',
        'spacer_21': 'Offer1250_spacer_21',
        'mobilelabel_15': 'Offer1250_mobilelabel_15',
        'spacer_16': 'Offer1250_spacer_16',
        'mobilelabel_23': 'Offer1250_mobilelabel_23',
        'mobilelabel_22': 'Offer1250_mobilelabel_22',
        'mobilelabel_24': 'Offer1250_mobilelabel_24',
        'spacer_25': 'Offer1250_spacer_25',
        'mobilelabel_13': 'Offer1250_mobilelabel_13',
        'mobilecollapsibleset_3': 'Offer1250_mobilecollapsibleset_3',
        'mobilecollapsblock_4': 'Offer1250_mobilecollapsblock_4',
        'mobilecollapsblockheader_5': 'Offer1250_mobilecollapsblockheader_5',
        'mobilecollapsblockcontent_6': 'Offer1250_mobilecollapsblockcontent_6',
        'mobilelabel_20': 'Offer1250_mobilelabel_20',
        'mobilebutton_17': 'Offer1250_mobilebutton_17',
        'mobilecollapsblock_7': 'Offer1250_mobilecollapsblock_7',
        'mobilecollapsblockheader_8': 'Offer1250_mobilecollapsblockheader_8',
        'mobilecollapsblockcontent_9': 'Offer1250_mobilecollapsblockcontent_9',
        'mobilebutton_18': 'Offer1250_mobilebutton_18',
        'mobilecollapsblock_10': 'Offer1250_mobilecollapsblock_10',
        'mobilecollapsblockheader_11': 'Offer1250_mobilecollapsblockheader_11',
        'mobilecollapsblockcontent_12': 'Offer1250_mobilecollapsblockcontent_12',
        'mobilebutton_19': 'Offer1250_mobilebutton_19'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Offer1250';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Offer1250_onLoad = function() {
            Offer1250_elementsExtraJS();

            Offer1250_deviceEvents();
            Offer1250_windowEvents();
            Offer1250_elementsEvents();
        };

    // screen window events


    function Offer1250_windowEvents() {

        $('#Offer1250').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Offer1250_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Offer1250_elementsExtraJS() {
        // screen (Offer1250) extra code

        /* mobilecollapsblock_4 */

        $("#Offer1250_mobilecollapsblock_4 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_7 */

        $("#Offer1250_mobilecollapsblock_7 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_10 */

        $("#Offer1250_mobilecollapsblock_10 .ui-collapsible-heading-toggle").attr("tabindex", "1");

    };

    // screen elements handler


    function Offer1250_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Offer1250_mobilecontainer [name="mobilebutton_17"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://github.com/blackaquaindia/TheBulkShoutout/raw/master/The_Bulk_Shoutout_Certified_v1.0.1_for_Android_4.1.2.apk', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');

                }
            },
        }, '#Offer1250_mobilecontainer [name="mobilebutton_17"]');

    };

    $(document).off("pagebeforeshow", "#Offer1250").on("pagebeforeshow", "#Offer1250", function(event, ui) {
        Apperyio.CurrentScreen = "Offer1250";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Offer1250_onLoad();
};

$(document).off("pagecreate", "#Offer1250").on("pagecreate", "#Offer1250", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Offer1250_js();
});
