/*
 * JS for trial generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '8d1c3d87-037c-46f1-9d3b-d76370ba131a';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "trial",
    "location": "trial.html"
}];

function trial_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_26': 'trial_mobilelabel_26',
        'spacer_27': 'trial_spacer_27',
        'mobilelabel_2': 'trial_mobilelabel_2',
        'mobilelabel_14': 'trial_mobilelabel_14',
        'spacer_21': 'trial_spacer_21',
        'mobilelabel_15': 'trial_mobilelabel_15',
        'spacer_16': 'trial_spacer_16',
        'mobilelabel_23': 'trial_mobilelabel_23',
        'mobilelabel_22': 'trial_mobilelabel_22',
        'mobilelabel_24': 'trial_mobilelabel_24',
        'spacer_25': 'trial_spacer_25',
        'mobilelabel_13': 'trial_mobilelabel_13',
        'mobilecollapsibleset_3': 'trial_mobilecollapsibleset_3',
        'mobilecollapsblock_4': 'trial_mobilecollapsblock_4',
        'mobilecollapsblockheader_5': 'trial_mobilecollapsblockheader_5',
        'mobilecollapsblockcontent_6': 'trial_mobilecollapsblockcontent_6',
        'mobilelabel_20': 'trial_mobilelabel_20',
        'mobilebutton_17': 'trial_mobilebutton_17',
        'mobilecollapsblock_7': 'trial_mobilecollapsblock_7',
        'mobilecollapsblockheader_8': 'trial_mobilecollapsblockheader_8',
        'mobilecollapsblockcontent_9': 'trial_mobilecollapsblockcontent_9',
        'mobilebutton_18': 'trial_mobilebutton_18',
        'mobilecollapsblock_10': 'trial_mobilecollapsblock_10',
        'mobilecollapsblockheader_11': 'trial_mobilecollapsblockheader_11',
        'mobilecollapsblockcontent_12': 'trial_mobilecollapsblockcontent_12',
        'mobilebutton_19': 'trial_mobilebutton_19'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'trial';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var trial_onLoad = function() {
            trial_elementsExtraJS();

            trial_deviceEvents();
            trial_windowEvents();
            trial_elementsEvents();
        };

    // screen window events


    function trial_windowEvents() {

        $('#trial').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function trial_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function trial_elementsExtraJS() {
        // screen (trial) extra code

        /* mobilecollapsblock_4 */

        $("#trial_mobilecollapsblock_4 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_7 */

        $("#trial_mobilecollapsblock_7 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_10 */

        $("#trial_mobilecollapsblock_10 .ui-collapsible-heading-toggle").attr("tabindex", "1");

    };

    // screen elements handler


    function trial_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#trial_mobilecontainer [name="mobilebutton_17"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://github.com/blackaquaindia/TheBulkShoutout/raw/master/The_Bulk_Shoutout_Certified_v1.0.1_for_Android_4.1.2.apk', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');

                }
            },
        }, '#trial_mobilecontainer [name="mobilebutton_17"]');

    };

    $(document).off("pagebeforeshow", "#trial").on("pagebeforeshow", "#trial", function(event, ui) {
        Apperyio.CurrentScreen = "trial";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    trial_onLoad();
};

$(document).off("pagecreate", "#trial").on("pagecreate", "#trial", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    trial_js();
});
