/*
 * JS for n4nikita generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '8d1c3d87-037c-46f1-9d3b-d76370ba131a';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "n4nikita",
    "location": "n4nikita.html"
}];

function n4nikita_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_26': 'n4nikita_mobilelabel_26',
        'spacer_27': 'n4nikita_spacer_27',
        'mobilelabel_2': 'n4nikita_mobilelabel_2',
        'mobilelabel_14': 'n4nikita_mobilelabel_14',
        'spacer_21': 'n4nikita_spacer_21',
        'mobilelabel_15': 'n4nikita_mobilelabel_15',
        'spacer_16': 'n4nikita_spacer_16',
        'mobilelabel_23': 'n4nikita_mobilelabel_23',
        'mobilelabel_22': 'n4nikita_mobilelabel_22',
        'mobilelabel_24': 'n4nikita_mobilelabel_24',
        'spacer_25': 'n4nikita_spacer_25',
        'mobilelabel_13': 'n4nikita_mobilelabel_13',
        'mobilecollapsibleset_3': 'n4nikita_mobilecollapsibleset_3',
        'mobilecollapsblock_4': 'n4nikita_mobilecollapsblock_4',
        'mobilecollapsblockheader_5': 'n4nikita_mobilecollapsblockheader_5',
        'mobilecollapsblockcontent_6': 'n4nikita_mobilecollapsblockcontent_6',
        'mobilelabel_20': 'n4nikita_mobilelabel_20',
        'mobilebutton_17': 'n4nikita_mobilebutton_17',
        'mobilecollapsblock_7': 'n4nikita_mobilecollapsblock_7',
        'mobilecollapsblockheader_8': 'n4nikita_mobilecollapsblockheader_8',
        'mobilecollapsblockcontent_9': 'n4nikita_mobilecollapsblockcontent_9',
        'mobilebutton_18': 'n4nikita_mobilebutton_18',
        'mobilecollapsblock_10': 'n4nikita_mobilecollapsblock_10',
        'mobilecollapsblockheader_11': 'n4nikita_mobilecollapsblockheader_11',
        'mobilecollapsblockcontent_12': 'n4nikita_mobilecollapsblockcontent_12',
        'mobilebutton_19': 'n4nikita_mobilebutton_19'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'n4nikita';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var n4nikita_onLoad = function() {
            n4nikita_elementsExtraJS();

            n4nikita_deviceEvents();
            n4nikita_windowEvents();
            n4nikita_elementsEvents();
        };

    // screen window events


    function n4nikita_windowEvents() {

        $('#n4nikita').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function n4nikita_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function n4nikita_elementsExtraJS() {
        // screen (n4nikita) extra code

        /* mobilecollapsblock_4 */

        $("#n4nikita_mobilecollapsblock_4 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_7 */

        $("#n4nikita_mobilecollapsblock_7 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_10 */

        $("#n4nikita_mobilecollapsblock_10 .ui-collapsible-heading-toggle").attr("tabindex", "1");

    };

    // screen elements handler


    function n4nikita_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#n4nikita_mobilecontainer [name="mobilebutton_17"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://github.com/blackaquaindia/TheBulkShoutout/raw/master/The_Bulk_Shoutout_Certified_v1.0.1_for_Android_4.1.2.apk', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');

                }
            },
        }, '#n4nikita_mobilecontainer [name="mobilebutton_17"]');

    };

    $(document).off("pagebeforeshow", "#n4nikita").on("pagebeforeshow", "#n4nikita", function(event, ui) {
        Apperyio.CurrentScreen = "n4nikita";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    n4nikita_onLoad();
};

$(document).off("pagecreate", "#n4nikita").on("pagecreate", "#n4nikita", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    n4nikita_js();
});
